repos:
  - repo: https://github.com/mattlqx/pre-commit-search-and-replace
    rev: v1.0.5
    hooks:
      - id: search-and-replace
        types: [markdown]
        exclude: themes/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
        types: [markdown]
        exclude: themes/
      - id: end-of-file-fixer
        types: [markdown]
        exclude: themes/
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint-fix
        types: [markdown]
        exclude: 'themes/.*|content/en/docs/getting_started/api-reference.md|content/en/docs/getting_started/template-reference.md'
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
        types: [markdown]
        exclude: 'themes/.*|content/en/docs/getting_started/api-reference.md'
